# Dockerfile for development

# Use the official Node 20 image as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the app source code to the working directory
COPY . .

# Expose the port on which your app will run
EXPOSE 3000

# Start the app in development mode
CMD [ "npm", "run" , "dev" ]
